### Get users
GET http://localhost:3000/api/v1/auth/usersList
Accept:application/json

### Register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json
Accept:application/json

{
    "firstName" : "YO",
    "lastName": "Lo",
    "email":"test222@test.com",
    "password": "testtestetest"
}


### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json
Accept: application/json

{
    "email":"test@test.com",
    "password": "testtestetest"
}


### Get conversation
GET http://localhost:3000/api/v1/slack/conversation/1
Content-Type: application/json
Accept:application/json

### Get conversations
GET http://localhost:3000/api/v1/slack/conversations
Content-Type: application/json
Accept:application/json

{
    "userId":2
}

### Create conversations
POST http://localhost:3000/api/v1/slack/conversations/create
Content-Type: application/json
Accept:application/json

{
  "conversationId": 2,
  "initiatorId": 2,
  "recipientId": 2,
  "conversationName": "aaaa"
}

### Rename conversation
PUT http://localhost:3000/api/v1/slack/conversations/1/rename
Accept:application/json

### Delete conversation
DELETE http://localhost:3000/api/v1/slack/conversations/1/delete
Accept:application/json



### Get messages
GET http://localhost:3000/api/v1/slack/conversations/1/messages
Accept:application/json

### Send message
POST http://localhost:3000/api/v1/slack/conversations/1/messages/send
Accept:application/json

### Edit message
PUT http://localhost:3000/api/v1/slack/conversations/1/messages/2/edit
Accept:application/json

### Replies to message
GET http://localhost:3000/api/v1/slack/conversations/1/messages/2/replies
Accept:application/json

### Parent message
GET http://localhost:3000/api/v1/slack/conversations/1/messages/2/parent
Accept:application/json

### Delete message
DELETE http://localhost:3000/api/v1/slack/conversations/1/messages/2/delete
Accept:application/json



### Reactions to message
GET http://localhost:3000/api/v1/slack/conversations/1/messages/2/reactions

### Add reaction
POST http://localhost:3000/api/v1/slack/conversations/1/messages/2/reactions/add
Accept:application/json

### Edit reaction
PUT http://localhost:3000/api/v1/slack/conversations/1/messages/2/reactions/2/edit
Accept:application/json

### Delete reaction
DELETE http://localhost:3000/api/v1/slack/conversations/1/messages/2/reactions/2/delete
Accept:application/json